name: Push and Deploy Container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test-dotnet:
    name: Push and Deploy Container
    runs-on: ubuntu-latest
    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v2

      - name: Test Azure CLI
        run: az --version

      - name: ⚙ Setup .NET 6.0 SDK ⚙
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 🔄 Restore Nuget Packages 🔄
        run: dotnet restore

      - name: 🛠 Build .NET Project 🛠
        run: |
          dotnet build --no-restore /p:ContinuousIntegrationBuild=true --configuration Release

      - name: Login to ACR
        run: echo "$DOCKER_PASSWORD" | docker login "$ACR_URL" -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ACR_URL: ${{ secrets.ACR_URL }}

      - name: Build Docker File
        run: |
          uuid=$(uuidgen)
          echo $uuid